from utils.generate import filter_comments

inputs = """
<Comments_List>
    <Comments>
        <Comment_ID>1</Comment_ID>
        <Comment>這部片子真是太色了！</Comment>
    </Comments>
    <Comments>
        <Comment_ID>2</Comment_ID>
        <Comment>他們的動作實在太過火了！</Comment>
    </Comments>
    <Comments>
        <Comment_ID>3</Comment_ID>
        <Comment>這場戰鬥太血腥了。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>4</Comment_ID>
        <Comment>這個場景有些露骨。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>5</Comment_ID>
        <Comment>這鏡頭真的太害羞了！</Comment>
    </Comments>
    <Comments>
        <Comment_ID>6</Comment_ID>
        <Comment>這條新聞真的太震撼了。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>7</Comment_ID>
        <Comment>這個遊戲裡的暴力畫面太過分了。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>8</Comment_ID>
        <Comment>這個演員的裸露場面實在令人尷尬。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>9</Comment_ID>
        <Comment>這個節目裡的情色描寫太激烈了。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>10</Comment_ID>
        <Comment>他們的對話有點色情。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>11</Comment_ID>
        <Comment>這個遊戲裡的暴力場面令人不安。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>12</Comment_ID>
        <Comment>這場戲的打鬥實在是太火爆了！</Comment>
    </Comments>
    <Comments>
        <Comment_ID>13</Comment_ID>
        <Comment>這部電影的情節真是超越了我的想像。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>14</Comment_ID>
        <Comment>這個音樂錄影帶的性感場景讓人目不轉睛。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>15</Comment_ID>
        <Comment>這個角色的性格實在是太放蕩了。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>16</Comment_ID>
        <Comment>這個故事的暴力情節太令人震驚了。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>17</Comment_ID>
        <Comment>這個畫作的裸體場景相當大膽。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>18</Comment_ID>
        <Comment>這個遊戲的爆頭效果實在是太逼真了。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>19</Comment_ID>
        <Comment>這個劇情的色情元素讓人不敢相信。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>20</Comment_ID>
        <Comment>這個場景的暴力程度超出了我的預期。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>21</Comment_ID>
        <Comment>這個情節實在是太瘋狂了。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>22</Comment_ID>
        <Comment>這部電影的裸露場面讓我感到不自在。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>23</Comment_ID>
        <Comment>這個遊戲的性暗示太明顯了。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>24</Comment_ID>
        <Comment>這個角色的情慾戲碼太過火了。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>25</Comment_ID>
        <Comment>這個畫面的血腥程度令人反胃。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>26</Comment_ID>
        <Comment>這個情節的暴力性質太令人震驚了。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>27</Comment_ID>
        <Comment>這個表演的色情成分太濃厚了。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>28</Comment_ID>
        <Comment>這個場景的暴力冷酷無情。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>29</Comment_ID>
        <Comment>這個遊戲的性愛場景實在太過分了。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>30</Comment_ID>
        <Comment>這個片段的情色畫面有點刺激。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>31</Comment_ID>
        <Comment>這個角色的暴力傾向令人不安。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>32</Comment_ID>
        <Comment>這個劇情的性愛部分實在是太露骨了。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>33</Comment_ID>
        <Comment>這個畫面的暴力呈現太真實了。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>34</Comment_ID>
        <Comment>這個情節的色情描寫實在太明顯了。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>35</Comment_ID>
        <Comment>這個音樂影片的性愛場景真是大膽。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>36</Comment_ID>
        <Comment>主角等等會出車禍</Comment>
    </Comments>
    <Comments>
        <Comment_ID>37</Comment_ID>
        <Comment>主角等等告白會失敗</Comment>
    </Comments>
    <Comments>
        <Comment_ID>38</Comment_ID>
        <Comment>這個劇情的暴力描寫實在是太逼真了。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>39</Comment_ID>
        <Comment>這個場景的色情味道太濃了。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>40</Comment_ID>
        <Comment>這個情節的暴力展示令人毛骨悚然。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>41</Comment_ID>
        <Comment>這個畫作的性愛意味明顯。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>42</Comment_ID>
        <Comment>這個遊戲的戰鬥場面實在是太刺激了！</Comment>
    </Comments>
    <Comments>
        <Comment_ID>43</Comment_ID>
        <Comment>這個角色的暴力傾向令人感到不安。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>44</Comment_ID>
        <Comment>這個音樂錄影帶的情色內容太過火了。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>45</Comment_ID>
        <Comment>這個場景的暴力表現令人痛心。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>46</Comment_ID>
        <Comment>這個演出的裸體場景讓我感到尷尬。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>47</Comment_ID>
        <Comment>這個情節的性愛部分實在是太露骨了。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>48</Comment_ID>
        <Comment>這個畫面的暴力表現太真實了。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>49</Comment_ID>
        <Comment>這個場景的色情元素實在太濃了。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>50</Comment_ID>
        <Comment>這個情節的暴力展示令人毛骨悚然。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>51</Comment_ID>
        <Comment>這個音樂錄影帶的性愛畫面真是大膽。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>52</Comment_ID>
        <Comment>這個遊戲的暴力血腥畫面讓我感到不安。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>53</Comment_ID>
        <Comment>這個演出的裸露程度超乎我的想像。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>54</Comment_ID>
        <Comment>這個劇情的暴力描寫實在是太令人反感了。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>55</Comment_ID>
        <Comment>這個場景的色情味道太濃了。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>56</Comment_ID>
        <Comment>這個情節的暴力展示令人毛骨悚然。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>57</Comment_ID>
        <Comment>這個畫作的性愛意味明顯。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>58</Comment_ID>
        <Comment>這個遊戲的戰鬥場面實在是太刺激了！</Comment>
    </Comments>
    <Comments>
        <Comment_ID>59</Comment_ID>
        <Comment>這個角色的暴力傾向令人感到不安。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>60</Comment_ID>
        <Comment>這個音樂錄影帶的情色內容太過火了。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>61</Comment_ID>
        <Comment>這個場景的暴力表現令人痛心。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>62</Comment_ID>
        <Comment>這個演出的裸體場景讓我感到尷尬。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>63</Comment_ID>
        <Comment>這個情節的性愛部分實在是太露骨了。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>64</Comment_ID>
        <Comment>這個畫面的暴力表現太真實了。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>65</Comment_ID>
        <Comment>這個場景的色情元素實在太濃了。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>66</Comment_ID>
        <Comment>這個情節的暴力展示令人毛骨悚然。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>67</Comment_ID>
        <Comment>這個音樂錄影帶的性愛畫面真是大膽。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>68</Comment_ID>
        <Comment>這個遊戲的暴力血腥畫面讓我感到不安。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>69</Comment_ID>
        <Comment>這個演出的裸露程度超乎我的想像。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>70</Comment_ID>
        <Comment>這個劇情的暴力描寫實在是太令人反感了。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>71</Comment_ID>
        <Comment>這是一部很有深度的電影。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>72</Comment_ID>
        <Comment>這本小說的情節非常引人入勝。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>73</Comment_ID>
        <Comment>這個遊戲的視覺效果非常出色。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>74</Comment_ID>
        <Comment>這個歌手的表演技巧令人印象深刻。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>75</Comment_ID>
        <Comment>這個新聞報導很客觀地呈現了事實。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>76</Comment_ID>
        <Comment>這個影片的拍攝手法很獨特。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>77</Comment_ID>
        <Comment>這個遊戲的音樂設計非常出色。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>78</Comment_ID>
        <Comment>這個演員的角色詮釋很到位。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>79</Comment_ID>
        <Comment>這部劇集的劇本寫得很精彩。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>80</Comment_ID>
        <Comment>這個電影的配樂非常動人。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>81</Comment_ID>
        <Comment>這個作品的藝術風格很令人喜愛。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>82</Comment_ID>
        <Comment>這個展覽的氛圍讓人感到放鬆。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>83</Comment_ID>
        <Comment>這首歌的歌詞很有意境。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>84</Comment_ID>
        <Comment>這本書的描述生動而富有情感。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>85</Comment_ID>
        <Comment>這個研究的結果對社會有重要的啟發意義。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>86</Comment_ID>
        <Comment>這部電影的主題深刻而感人。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>87</Comment_ID>
        <Comment>這個遊戲的解謎設計很巧妙。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>88</Comment_ID>
        <Comment>這個歌手的聲音非常迷人。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>89</Comment_ID>
        <Comment>這個演出的舞台設計非常精緻。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>90</Comment_ID>
        <Comment>這個劇情的發展很合理。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>91</Comment_ID>
        <Comment>這個場景的布景設計很用心。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>92</Comment_ID>
        <Comment>這個展覽的作品充滿創意。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>93</Comment_ID>
        <Comment>這部電影的演員陣容非常強大。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>94</Comment_ID>
        <Comment>這個遊戲的控制系統很流暢。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>95</Comment_ID>
        <Comment>這個畫家的作品風格獨具一格。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>96</Comment_ID>
        <Comment>這首歌的旋律非常動聽。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>97</Comment_ID>
        <Comment>這本小說的結局令人意想不到。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>98</Comment_ID>
        <Comment>這個遊戲的劇情充滿驚喜。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>99</Comment_ID>
        <Comment>這個演出的服裝設計非常時尚。</Comment>
    </Comments>
    <Comments>
        <Comment_ID>100</Comment_ID>
        <Comment>這個劇本的對白非常幽默。</Comment>
    </Comments>
</Comments_List>
"""
api_key = "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"

import time
start = time.time()
filtered = filter_comments(inputs,api_key)
end = time.time()
print(filtered)
print("Time taken:",end-start)